availableSecrets:
  secretManager:
  - versionName: projects/my-hello-cb/secrets/dockerhub-username/versions/latest
    env: _DOCKERHUB_USERNAME
  - versionName: projects/my-hello-cb/secrets/dockerhub-password/versions/latest
    env: _DOCKERHUB_PASSWORD

steps:
  # Step 1: Build JAR with Maven
  - id: "Build with Maven"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['clean', 'package']

  # Step 2: Run tests
  - id: "Run Tests"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['test']

  # Step 3: Docker login (non-interactive)
  - id: "Docker Hub Login"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['_DOCKERHUB_USERNAME', '_DOCKERHUB_PASSWORD']
    args:
      - -c
      - |
        echo "$_DOCKERHUB_PASSWORD" | docker login -u "$_DOCKERHUB_USERNAME" --password-stdin

  # Step 4: Build Docker image
  - id: "Build Docker Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t", "docker.io/my-dockerhub-user/myapp:2.0-SNAPSHOT",
        "."
      ]

  # Step 5: Push Docker image
  - id: "Push Docker Image"
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "docker.io/my-dockerhub-user/myapp:2.0-SNAPSHOT"]

options:
  logging: CLOUD_LOGGING_ONLY
