steps:
  # Step 1: Compile and package with Java 21 + Maven 3.9.9
  - id: "Build with Maven"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['clean', 'package']

  # Step 2: Run tests
  - id: "Run Tests"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['test']

# Logging fix for custom service account
options:
  logging: CLOUD_LOGGING_ONLY

