steps:
  # Step 1: Compile and package with Java 21 + Maven 3.9.9
  - id: "Build with Maven"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['clean', 'package']
    volumes:
      - name: 'maven-cache'
        path: '/root/.m2'

  # Step 2: Run tests
  - id: "Run Tests"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['test']
    volumes:
      - name: 'maven-cache'
        path: '/root/.m2'

options:
  logging: CLOUD_LOGGING_ONLY

caches:
  - path: /root/.m2

