steps:
  # Step 1: Compile and package with Java 21 + Maven 3.9.9
  - id: "Build with Maven"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['clean', 'package']

  # Step 2: Run tests
  - id: "Run Tests"
    name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: mvn
    args: ['test']

  # Step 3: Authenticate to Docker Hub
  - id: "Docker Hub Auth"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker login -u $(gcloud secrets versions access latest --secret="dockerhub-username") \
          -p $(gcloud secrets versions access latest --secret="dockerhub-password")

  # Step 4: Build Docker image
  - id: "Build Docker Image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t", "docker.io/my-dockerhub-user/myapp:2.0-SNAPSHOT",
        "."
      ]

  # Step 5: Push Docker image
  - id: "Push Docker Image"
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "docker.io/my-dockerhub-user/myapp:2.0-SNAPSHOT"]

options:
  logging: CLOUD_LOGGING_ONLY
