apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80        # Port the load balancer will listen on
      targetPort: 8080 # Port your application is listening on
